### ISSUE TITLE
Event Pin always high and AT+EVENT? response always 1005

### ISSUE THREAD

**Issue by asierdanjou** [vikramdattu/ExpressLink-Host#1]
Hi, 
I'm just testing dimmer device with ExL on esp32-c6-devkitm-1 board.
I flash the part with ESPLAUNCH webusb and now I'm doing test with two TeraTerm terminal in windows. One of them to recieve concole messages and the other one to send AT commands like a MCU host would do.
My issue is that I send "AT+EVENT?" ExL module always reponses "OK 1005 0 MATTER ATTRIBUTE UPDATE".
Then, I send "AT+MATTER GET ATTRIBUTE_UPDATE" and I receive "OK", so no more attributes to update leaves. Nonetheless, I receive "OK 1005 0 MATTER ATTRIBUTE UPDATE",  Why?

Thank you,
Asier.

**Comment by vikramdattu** [comment]
Hi @asierdanjou 

Apologies for the late reply. I discussed your issue with the concerned team and according to them, issue shouldn't been there. 
Did you find the root cause for your issue?

**Comment by asierdanjou** [comment]
Hi Vikramdattu/Expresslink-Host,
This issue was solved., so I closed it.
I've opened another one with other topic.
Thank you,
Asier.
